development:
  adapter: postgresql
  encoding: unicode
  database: tddyelp_development
  pool: 5
  username: tddyelp
  password: password1
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: tddyelp_test
  pool: 5
  username: tddyelp
  password: password1
  host: localhost
  port: 5432
